sudo: false
dist: focal
language: python

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7.13"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8.13"
      env: TOXENV=py38
    - python: "3.9.12"
      env: TOXENV=py39
    - python: "3.10.4"
      env: TOXENV=py310

  allow_failures:
    - env: TOXENV=py36
    - env: TOXENV=py310

install:
  - pip install virtualenv
  - pip install tox-travis

script:
  - tox -e $TOXENV
