language: python
python: 2.7
before_script:
  - pep8 currencycloud
script: tox -e $TOX_ENV
install:
  - pip install tox
  - pip install pep8
notifications:
  email: false
env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
