language: python

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'

install:
  - pip install -r requirements.txt

script: pytest
