sudo: false

language: python

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
  allow_failures:
    - env: TOXENV=py33

install:
  - pip install virtualenv
  - pip install tox-travis

script:
  - tox -e $TOXENV
