language: python
python: 2.7
script: tox -e $TOX_ENV
install:
  - pip install tox
notifications:
  email: false
env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
